name             'sisense'
maintainer       'Topher Cullen'
maintainer_email 'topher.cullen@jamberry.com'
license          'Apache 2.0'
description      'Installs/Configures sisense'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

supports 'ubuntu', '>= 10.04'
supports 'debian', '>= 6.0'
supports 'redhat', '>= 5.0'
supports 'centos', '>= 5.0'
supports 'windows'
depends 'mongodb'
depends 'iis'
depends 'windows'
depends 'vcruntime'
depends 'partial_search'
depends 'chocolatey'
depends 'windows_firewall'
